name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile with dragon
        uses: DragonBuild/build@master
      
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: packages/*.deb
